version: '3.8'

services: 
  backend: 
    image: myrepo/my-backend:latest
    ports: 
      - "8000:8000"
    env_file:
      - ../backend/.env
    depends_on:
      - db

  frontend: 
    image: myrepo/my-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  db: 
    image: postgres:14
    env_file: 
      - ../backend/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: