name: React Frontend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Code aus Repo holen
      - name: Checkout code
        uses: actions/checkout@v3

      # Node.js installieren
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Abhängigkeiten installieren
      - name: Install dependencies
        run: |
          cd frontend
          npm install

      # Linter und Tests ausführen
      - name: Run lint and tests
        run: |
          cd frontend
          npm run lint
          npm test

      # Frontend bauen
      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # Login bei DockerHub mit der Docker Action
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker Image bauen und pushen
      - name: Build and push Docker image
        run: |
          docker build -t CaroWithoutE/myrepo-frontend:latest ./frontend
          docker push CaroWithoutE/myrepo-frontend:latest

      # Auf Vercel deployen
      - name: Deploy to Vercel
        if: success()
        run: |
          npm install -g vercel
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
